class GeoClassificationDefinitions:
    
    conversion = [{'alpha2': 'AF', 'alpha3': 'AFG', 'name': 'Afghanistan', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AL', 'alpha3': 'ALB', 'name': 'Albania', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'DZ', 'alpha3': 'DZA', 'name': 'Algeria', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AS', 'alpha3': 'ASM', 'name': 'American Samoa', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AO', 'alpha3': 'AGO', 'name': 'Angola', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AI', 'alpha3': 'AIA', 'name': 'Anguilla', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AQ', 'alpha3': 'ATA', 'name': 'Antarctica', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AG', 'alpha3': 'ATG', 'name': 'Antigua and Barbuda', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AR', 'alpha3': 'ARG', 'name': 'Argentina', 'region': 'Latin America', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AM', 'alpha3': 'ARM', 'name': 'Armenia', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AW', 'alpha3': 'ABW', 'name': 'Aruba', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AU', 'alpha3': 'AUS', 'name': 'Australia', 'region': 'Other Asia', 'rcg_geo_bucket': 'Other Asia', 'market_tp': 'Developed Market'},
    {'alpha2': 'AT', 'alpha3': 'AUT', 'name': 'Austria', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'AZ', 'alpha3': 'AZE', 'name': 'Azerbaijan', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BS', 'alpha3': 'BHS', 'name': 'Bahamas', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BH', 'alpha3': 'BHR', 'name': 'Bahrain', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BD', 'alpha3': 'BGD', 'name': 'Bangladesh', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BB', 'alpha3': 'BRB', 'name': 'Barbados', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BY', 'alpha3': 'BLR', 'name': 'Belarus', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BE', 'alpha3': 'BEL', 'name': 'Belgium', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'BZ', 'alpha3': 'BLZ', 'name': 'Belize', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BJ', 'alpha3': 'BEN', 'name': 'Benin', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BM', 'alpha3': 'BMU', 'name': 'Bermuda', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BT', 'alpha3': 'BTN', 'name': 'Bhutan', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BO', 'alpha3': 'BOL', 'name': 'Bolivia', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BA', 'alpha3': 'BIH', 'name': 'Bosnia and Herzegovina', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BW', 'alpha3': 'BWA', 'name': 'Botswana', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BR', 'alpha3': 'BRA', 'name': 'Brazil', 'region': 'Latin America', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'IO', 'alpha3': 'IOT', 'name': 'British Indian Ocean Territory', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BN', 'alpha3': 'BRN', 'name': 'Brunei Darussalam', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BG', 'alpha3': 'BGR', 'name': 'Bulgaria', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BF', 'alpha3': 'BFA', 'name': 'Burkina Faso', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'BI', 'alpha3': 'BDI', 'name': 'Burundi', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KH', 'alpha3': 'KHM', 'name': 'Cambodia', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CM', 'alpha3': 'CMR', 'name': 'Cameroon', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CA', 'alpha3': 'CAN', 'name': 'Canada', 'region': 'North America', 'rcg_geo_bucket': 'North America', 'market_tp': 'Developed Market'},
    {'alpha2': 'CV', 'alpha3': 'CPV', 'name': 'Cape Verde', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KY', 'alpha3': 'CYM', 'name': 'Cayman Islands', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CF', 'alpha3': 'CAF', 'name': 'Central African Republic', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TD', 'alpha3': 'TCD', 'name': 'Chad', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CL', 'alpha3': 'CHL', 'name': 'Chile', 'region': 'Latin America', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'CN', 'alpha3': 'CHN', 'name': 'China', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'HK', 'alpha3': 'HKG', 'name': 'Hong Kong', 'region': 'Other Asia', 'rcg_geo_bucket': 'Other Asia', 'market_tp': 'Developed Market'},
    {'alpha2': 'CX', 'alpha3': 'CXR', 'name': 'Christmas Island', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CC', 'alpha3': 'CCK', 'name': 'Cocos (Keeling) Islands', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CO', 'alpha3': 'COL', 'name': 'Colombia', 'region': 'Latin America', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'KM', 'alpha3': 'COM', 'name': 'Comoros', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CG', 'alpha3': 'COG', 'name': 'Congo', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CD', 'alpha3': 'COD', 'name': 'Congo', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CK', 'alpha3': 'COK', 'name': 'Cook Islands', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CR', 'alpha3': 'CRI', 'name': 'Costa Rica', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'HR', 'alpha3': 'HRV', 'name': 'Croatia', 'region': 'Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CU', 'alpha3': 'CUB', 'name': 'Cuba', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'CY', 'alpha3': 'CYP', 'name': 'Cyprus', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'CZ', 'alpha3': 'CZE', 'name': 'Czech Republic', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'DK', 'alpha3': 'DNK', 'name': 'Denmark', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'DJ', 'alpha3': 'DJI', 'name': 'Djibouti', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'DM', 'alpha3': 'DMA', 'name': 'Dominica', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'DO', 'alpha3': 'DOM', 'name': 'Dominican Republic', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'EC', 'alpha3': 'ECU', 'name': 'Ecuador', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'EG', 'alpha3': 'EGY', 'name': 'Egypt', 'region': 'Africa', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'SV', 'alpha3': 'SLV', 'name': 'El Salvador', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GQ', 'alpha3': 'GNQ', 'name': 'Equatorial Guinea', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'ER', 'alpha3': 'ERI', 'name': 'Eritrea', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'EE', 'alpha3': 'EST', 'name': 'Estonia', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'ET', 'alpha3': 'ETH', 'name': 'Ethiopia', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'FJ', 'alpha3': 'FJI', 'name': 'Fiji', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'FI', 'alpha3': 'FIN', 'name': 'Finland', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'FR', 'alpha3': 'FRA', 'name': 'France', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'GF', 'alpha3': 'GUF', 'name': 'French Guiana', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GA', 'alpha3': 'GAB', 'name': 'Gabon', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GM', 'alpha3': 'GMB', 'name': 'Gambia', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GE', 'alpha3': 'GEO', 'name': 'Georgia', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'DE', 'alpha3': 'DEU', 'name': 'Germany', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'GH', 'alpha3': 'GHA', 'name': 'Ghana', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GR', 'alpha3': 'GRC', 'name': 'Greece', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'GD', 'alpha3': 'GRD', 'name': 'Grenada', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GU', 'alpha3': 'GUM', 'name': 'Guam', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GT', 'alpha3': 'GTM', 'name': 'Guatemala', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GN', 'alpha3': 'GIN', 'name': 'Guinea', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GW', 'alpha3': 'GNB', 'name': 'Guinea-Bissau', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'GY', 'alpha3': 'GUY', 'name': 'Guyana', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'HT', 'alpha3': 'HTI', 'name': 'Haiti', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'HN', 'alpha3': 'HND', 'name': 'Honduras', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'HU', 'alpha3': 'HUN', 'name': 'Hungary', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'IN', 'alpha3': 'IND', 'name': 'India', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'ID', 'alpha3': 'IDN', 'name': 'Indonesia', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'IR', 'alpha3': 'IRN', 'name': 'Iran', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'IQ', 'alpha3': 'IRQ', 'name': 'Iraq', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'IE', 'alpha3': 'IRL', 'name': 'Ireland', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'IL', 'alpha3': 'ISR', 'name': 'Israel', 'region': 'Middle East', 'rcg_geo_bucket': 'Other', 'market_tp': 'Developed Market'},
    {'alpha2': 'IT', 'alpha3': 'ITA', 'name': 'Italy', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'JM', 'alpha3': 'JAM', 'name': 'Jamaica', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'JP', 'alpha3': 'JPN', 'name': 'Japan', 'region': 'Japan', 'rcg_geo_bucket': 'Japan', 'market_tp': 'Developed Market'},
    {'alpha2': 'JE', 'alpha3': 'JEY', 'name': 'Jersey', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'JO', 'alpha3': 'JOR', 'name': 'Jordan', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KZ', 'alpha3': 'KAZ', 'name': 'Kazakhstan', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KE', 'alpha3': 'KEN', 'name': 'Kenya', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KI', 'alpha3': 'KIR', 'name': 'Kiribati', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KR', 'alpha3': 'KOR', 'name': 'South Korea', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'KW', 'alpha3': 'KWT', 'name': 'Kuwait', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KG', 'alpha3': 'KGZ', 'name': 'Kyrgyzstan', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'LV', 'alpha3': 'LVA', 'name': 'Latvia', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'LB', 'alpha3': 'LBN', 'name': 'Lebanon', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'LS', 'alpha3': 'LSO', 'name': 'Lesotho', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'LR', 'alpha3': 'LBR', 'name': 'Liberia', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'LT', 'alpha3': 'LTU', 'name': 'Lithuania', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'LU', 'alpha3': 'LUX', 'name': 'Luxembourg', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'MG', 'alpha3': 'MDG', 'name': 'Madagascar', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MW', 'alpha3': 'MWI', 'name': 'Malawi', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MY', 'alpha3': 'MYS', 'name': 'Malaysia', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'MV', 'alpha3': 'MDV', 'name': 'Maldives', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'ML', 'alpha3': 'MLI', 'name': 'Mali', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MT', 'alpha3': 'MLT', 'name': 'Malta', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'MH', 'alpha3': 'MHL', 'name': 'Marshall Islands', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MQ', 'alpha3': 'MTQ', 'name': 'Martinique', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MR', 'alpha3': 'MRT', 'name': 'Mauritania', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MU', 'alpha3': 'MUS', 'name': 'Mauritius', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MX', 'alpha3': 'MEX', 'name': 'Mexico', 'region': 'Latin America', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'FM', 'alpha3': 'FSM', 'name': 'Micronesia, Federated States of', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MN', 'alpha3': 'MNG', 'name': 'Mongolia', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MS', 'alpha3': 'MSR', 'name': 'Montserrat', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MA', 'alpha3': 'MAR', 'name': 'Morocco', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MZ', 'alpha3': 'MOZ', 'name': 'Mozambique', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'nan', 'alpha3': 'NAM', 'name': 'Namibia', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NR', 'alpha3': 'NRU', 'name': 'Nauru', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NP', 'alpha3': 'NPL', 'name': 'Nepal', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NL', 'alpha3': 'NLD', 'name': 'Netherlands', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'NZ', 'alpha3': 'NZL', 'name': 'New Zealand', 'region': 'Other Asia', 'rcg_geo_bucket': 'Other Asia', 'market_tp': 'Developed Market'},
    {'alpha2': 'NI', 'alpha3': 'NIC', 'name': 'Nicaragua', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NE', 'alpha3': 'NER', 'name': 'Niger', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NG', 'alpha3': 'NGA', 'name': 'Nigeria', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NU', 'alpha3': 'NIU', 'name': 'Niue', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NF', 'alpha3': 'NFK', 'name': 'Norfolk Island', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'MP', 'alpha3': 'MNP', 'name': 'Northern Mariana Islands', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'NO', 'alpha3': 'NOR', 'name': 'Norway', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'OM', 'alpha3': 'OMN', 'name': 'Oman', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'PK', 'alpha3': 'PAK', 'name': 'Pakistan', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'PW', 'alpha3': 'PLW', 'name': 'Palau', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'PA', 'alpha3': 'PAN', 'name': 'Panama', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'PG', 'alpha3': 'PNG', 'name': 'Papua New Guinea', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'PY', 'alpha3': 'PRY', 'name': 'Paraguay', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'PE', 'alpha3': 'PER', 'name': 'Peru', 'region': 'Latin America', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'PH', 'alpha3': 'PHL', 'name': 'Philippines', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'PL', 'alpha3': 'POL', 'name': 'Poland', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'PT', 'alpha3': 'PRT', 'name': 'Portugal', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'PR', 'alpha3': 'PRI', 'name': 'Puerto Rico', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'QA', 'alpha3': 'QAT', 'name': 'Qatar', 'region': 'Middle East', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'RO', 'alpha3': 'ROU', 'name': 'Romania', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'RU', 'alpha3': 'RUS', 'name': 'Russia', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'RW', 'alpha3': 'RWA', 'name': 'Rwanda', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'KN', 'alpha3': 'KNA', 'name': 'Saint Kitts and Nevis', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'LC', 'alpha3': 'LCA', 'name': 'Saint Lucia', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'WS', 'alpha3': 'WSM', 'name': 'Samoa', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'ST', 'alpha3': 'STP', 'name': 'Sao Tome and Principe', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SA', 'alpha3': 'SAU', 'name': 'Saudi Arabia', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SN', 'alpha3': 'SEN', 'name': 'Senegal', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'RS', 'alpha3': 'SRB', 'name': 'Serbia', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SC', 'alpha3': 'SYC', 'name': 'Seychelles', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SL', 'alpha3': 'SLE', 'name': 'Sierra Leone', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SG', 'alpha3': 'SGP', 'name': 'Singapore', 'region': 'Other Asia', 'rcg_geo_bucket': 'Other Asia', 'market_tp': 'Developed Market'},
    {'alpha2': 'SK', 'alpha3': 'SVK', 'name': 'Slovakia', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'SI', 'alpha3': 'SVN', 'name': 'Slovenia', 'region': 'Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SB', 'alpha3': 'SLB', 'name': 'Solomon Islands', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SO', 'alpha3': 'SOM', 'name': 'Somalia', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'ZA', 'alpha3': 'ZAF', 'name': 'South Africa', 'region': 'Africa', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'ES', 'alpha3': 'ESP', 'name': 'Spain', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'LK', 'alpha3': 'LKA', 'name': 'Sri Lanka', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SD', 'alpha3': 'SDN', 'name': 'Sudan', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SR', 'alpha3': 'SUR', 'name': 'Suriname', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SZ', 'alpha3': 'SWZ', 'name': 'Swaziland', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'SE', 'alpha3': 'SWE', 'name': 'Sweden', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'CH', 'alpha3': 'CHE', 'name': 'Switzerland', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'TW', 'alpha3': 'TWN', 'name': 'Taiwan', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'TJ', 'alpha3': 'TJK', 'name': 'Tajikistan', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TH', 'alpha3': 'THA', 'name': 'Thailand', 'region': 'Asia', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'TG', 'alpha3': 'TGO', 'name': 'Togo', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TK', 'alpha3': 'TKL', 'name': 'Tokelau', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TO', 'alpha3': 'TON', 'name': 'Tonga', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TT', 'alpha3': 'TTO', 'name': 'Trinidad and Tobago', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TN', 'alpha3': 'TUN', 'name': 'Tunisia', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TR', 'alpha3': 'TUR', 'name': 'Turkey', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'TM', 'alpha3': 'TKM', 'name': 'Turkmenistan', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TC', 'alpha3': 'TCA', 'name': 'Turks and Caicos Islands', 'region': 'Other', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'TV', 'alpha3': 'TUV', 'name': 'Tuvalu', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'UG', 'alpha3': 'UGA', 'name': 'Uganda', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'UA', 'alpha3': 'UKR', 'name': 'Ukraine', 'region': 'Eastern Europe', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'AE', 'alpha3': 'ARE', 'name': 'United Arab Emirates', 'region': 'Middle East', 'rcg_geo_bucket': 'Emerging Market', 'market_tp': 'Emerging Market'},
    {'alpha2': 'GB', 'alpha3': 'GBR', 'name': 'United Kingdom', 'region': 'Europe', 'rcg_geo_bucket': 'Europe', 'market_tp': 'Developed Market'},
    {'alpha2': 'US', 'alpha3': 'USA', 'name': 'United States', 'region': 'North America', 'rcg_geo_bucket': 'North America', 'market_tp': 'Developed Market'},
    {'alpha2': 'UY', 'alpha3': 'URY', 'name': 'Uruguay', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'UZ', 'alpha3': 'UZB', 'name': 'Uzbekistan', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'VU', 'alpha3': 'VUT', 'name': 'Vanuatu', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'VE', 'alpha3': 'VEN', 'name': 'Venezuela', 'region': 'Latin America', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'VN', 'alpha3': 'VNM', 'name': 'Vietnam', 'region': 'Asia', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'EH', 'alpha3': 'ESH', 'name': 'Western Sahara', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'YE', 'alpha3': 'YEM', 'name': 'Yemen', 'region': 'Middle East', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'ZM', 'alpha3': 'ZMB', 'name': 'Zambia', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'},
    {'alpha2': 'ZW', 'alpha3': 'ZWE', 'name': 'Zimbabwe', 'region': 'Africa', 'rcg_geo_bucket': 'Frontier Market', 'market_tp': 'Frontier Market'}]
